---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kratix-workload-resources
  namespace: flux-system
spec:
  interval: 5s
  url: https://172.18.0.2:31333/gitea_admin/kratix
  ref:
    branch: main
  secretRef:
    name: gitea-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kratix-workload-resources
  namespace: flux-system
spec:
  interval: 3s
  dependsOn:
    - name: kratix-workload-dependencies
  sourceRef:
    kind: GitRepository
    name: kratix-workload-resources
  path: "worker-1/resources/"
  prune: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kratix-workload-dependencies
  namespace: flux-system
spec:
  interval: 5s
  url: https://172.18.0.2:31333/gitea_admin/kratix
  ref:
    branch: main
  secretRef:
    name: gitea-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kratix-workload-dependencies
  namespace: flux-system
spec:
  interval: 8s
  sourceRef:
    kind: GitRepository
    name: kratix-workload-dependencies
  path: "worker-1/dependencies/"
  prune: true
